---
#- name: "install some packages"
#  package:
#    name: npm
#    state: latest

- name: install repo watchdog for toto
  tags: repowatchdog
  ansible.builtin.git: repo={{ item.repo }} dest={{ item.dest }} clone=yes update=yes force=yes
  with_items:
  - { repo: 'https://github.com/toto240325/watchdog.git', dest: '/home/toto/watchdog' }
  register: repo_watchdog

- name: "Copy params.py"
  template:
    src: "files/params.py.j2"
    dest: "/home/toto/watchdog/params.py"

- name: change ownership
  tags: repowatchdog
  file: path={{ item.path }} owner="toto" group="toto" state=directory recurse=yes mode="u=rwX,g=rX,o=rX"
  with_items:
  - { path: "/home/toto/watchdog" }
  #register: output_chown
  when: repo_watchdog.changed

# - name: "initialise DB in separate location (makes sense only for sqlite, not mysql)"
#   file: 
#     path: /home/toto/db
#     state: directory
#     owner: toto
#     group: toto
#   when: repo_monitor.changed


- name: set the SHELL cron variable
  tags: debug49
  community.general.cronvar:
    user: toto
    name: SHELL
    value: /bin/bash
    
- name: set the BASH_ENV cron variable
  tags: debug49
  community.general.cronvar:
    user: toto
    name: BASH_ENV
    value: /home/toto/.bashrc_conda
    insertafter: SHELL
    
- name: cron job to launch watchdog under toto
  tags: debug49
  cron:
    user: toto
    name: "watchdog"
    #special_time: reboot
    #minute: "*/5"
    minute: "0"
    job: "conda activate watchdog; /usr/local/bin/python /home/toto/watchdog/watchdog.py 2>&1 >> /home/toto/watchdog.log; conda deactivate"
