---
#- name: "install some packages"
#  package:
#    name: npm
#    state: latest

- name: install repo watchdog for toto
  tags: repowatchdog
  ansible.builtin.git: repo={{ item.repo }} dest={{ item.dest }} clone=yes update=yes force=yes
  with_items:
  - { repo: 'https://github.com/toto240325/watchdog.git', dest: '/home/toto/watchdog' }
  register: repo_watchdog

- name: "Copy params.py"
  template:
    src: "files/params.py.j2"
    dest: "/home/toto/watchdog/params.py"

- name: change ownership
  tags: repowatchdog
  file: path={{ item.path }} owner="toto" group="toto" state=directory recurse=yes mode="u=rwX,g=rX,o=rX"
  with_items:
  - { path: "/home/toto/watchdog" }
  #register: output_chown
  when: repo_watchdog.changed

# - name: "initialise DB in separate location (makes sense only for sqlite, not mysql)"
#   file: 
#     path: /home/toto/db
#     state: directory
#     owner: toto
#     group: toto
#   when: repo_monitor.changed


- name: cron job to launch watchdog under root
  cron:
    user: root
    name: "watchdog"
    #special_time: reboot
    minute: "*/5"
    job: "/usr/local/bin/python /home/toto/watchdog/watchdog.py 2>&1 >> /root/watchdog.log"
