---
- name: "install sqlite"
  package: name={{ item }} state=latest
  with_items:
    - sqlite3
    - php-sqlite3

- name: "create sqlite /opt/db folder"
  tags: opt_db
  file: 
    path: /opt/db
    state: directory
    owner: toto       # to be fixed one day
    group: www-data
    mode: '0775'

- name: check if mydatabase.db (sqlite) already exists
  tags: sqlite_db
  stat:
    path: /opt/db/mydatabase.db
  register: stat_result

- name: "install empty sqlite db"
  tags: sqlite_db
  copy: src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
  with_items:
  - { src: "mydatabase.db", dest: "/opt/db/mydatabase.db", owner: "toto", group: "www-data", mode: "774" }  # toto owner : to be fixed one day
  - { src: "mydatabase_dev.db", dest: "/opt/db/mydatabase_dev.db", owner: "toto", group: "www-data", mode: "774" }
  when: not stat_result.stat.exists



