---
- hosts: localhost
  connection: local
  become: true
  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
        upgrade : yes
      changed_when: False


  # tasks:
  # - name: install htop
  #   package:
  #     name: htop
  
  # - name: "debug msg"
  #   debug: msg="this is a debug message"

  # - name: "shell test"
  #   shell: "ls -la"
  #   register: shelloutput

  # - name: "debug shell output"
  #   debug: var=shelloutput

#    - import_tasks: tasks/users.yml
#    - import_tasks: tasks/cron.yml
#    - import_tasks: tasks/packages.yml

