---
#requirements
#ansible-galaxy install -r requirements.yml

collections:
- name: community.general
- name: ansible.windows
- name: ansible.utils

roles:
# Install a role from Ansible Galaxy.
# - name: geerlingguy.java
#   version: 1.9.6
- name: geerlingguy.apache
- name: geerlingguy.composer
- name: geerlingguy.mysql
- name: geerlingguy.php
- name: geerlingguy.php-mysql
- name: geerlingguy.postfix
- name: evandam.conda
- name: gantsign.keyboard
  
# collections:
#   # Install a collection from Ansible Galaxy.
#   - name: geerlingguy.php_roles
#     version: 0.9.3
#     source: https://galaxy.ansible.com


# - src: geerlingguy.apache
# - src: geerlingguy.composer
# - src: geerlingguy.mysql
# - src: geerlingguy.php
# - src: geerlingguy.php-mysql
# - src: geerlingguy.postfix
