---
# ansible-playbook site.yml --vault-password-file  ~/.ssh/vault-key
# ansible-playbook site.yml --tags apache
# ansible-playbook site.yml --limit ubuntu0


- hosts: all
  become: true
  vars_files:
  - ~/ansible/info.yml
  pre_tasks:

#  - debug:
#      var: ansible_facts["cmdline"]
#  - debug:
#      var: ansible_facts["machine"]
#  - debug:
#      var: ansible_facts["machine"]|type_debug
#  - debug:
#      var: ansible_distribution


  - name: install updates (Ubuntu) (and this is my {{ title }}
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Ubuntu","Debian"] # and ansible_distribution_version == "20.04"


- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 package (Ubuntu)
    tags: apache
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Ubuntu","Debian"] # and ansible_distribution_version == "20.04"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb server
    tags: db
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution in ["Ubuntu","Debian"] # and ansible_distribution_version == "20.04"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    package:
      name: samba
      state: latest

- hosts: ubuntu0
  become: true
  tasks:

  - name: install 7z
    package:
      name: p7zip-full
      state: latest

- hosts: adduser
  become: true
  tasks:

  - name: create toto2 user
    user: 
      name: toto2
      groups: root
      
