---
# ansible all --limit 192.168.0.51 -u vagrant -m "shell" -a "ls -al"
# ansible windows -m win_ping --ask-pass

# ansible -v webservers -m copy -a "src=dist/ dest=/var/www/html" -i inventory --become
# ansible-galaxy collection install community.general
# ansible-galaxy install -r requirements.yml # apparently this doesn't install collections ??
# ansible-galaxy collection install community.general
# ansible-galaxy collection install ansible.utils
# ansible-playbook site.yml --vault-password-file  ~/.ssh/vault-key # until ansible user created on target and accessible via ssh key
# ansible-playbook site.yml --tags apache
# ansible-playbook site.yml --limit ubuntu0
# ansible-playbook site.yml --limit 
# ansible-playbook site.yml  --tags=db_servers --skip-tags=always
# ansible-playbook site.yml  --tags=db_servers --skip-tags=always --list-tasks
# ansible-playbook site.yml --limit bootstrap --tags=bootstrap --skip-tags=always --ask-become-pass 
# ansible-vault edit ~/ansible/info.yml --vault-password-file  ~/.ssh/vault-key
# ansible-vault edit ~/ansible/vault.yml --vault-password-file  ~/.ssh/vault-key
# ansible-vault edit ~/ansible/roles/watchdog/vars/main.yml --vault-password-file  ~/.ssh/vault-key
#

# - hosts: 192.168.0.51
#   gather_facts: true
#   tasks:
#   # - name: "display all ansible_facts"
#   #   debug: var=ansible_facts
#   #   tags: debugfacts

#   - name: "check allfacts"
#     tags: debugfacts
#     debug: var=ansible_facts

#   - debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']

# - hosts: 192.168.0.52
#   tags: debug76
#   gather_facts: true
#   vars_files:
#   - ~/ansible/vault.yml
#   become: true
#   tasks:
#   - shell: "ls -al"
#     register: myoutput
#   - debug: var=myoutput

# - name: "register facts"
#   command: echo "test"
#   register: allfacts

- hosts: all
  tags: facts
  gather_facts: true
  vars_files:
  - ~/ansible/vault.yml
  become: true
  tasks:
#  - debug: var=ansible_facts["architecture"]
  - debug: var=ansible_facts["all_ipv4_addresses"]
  - debug: var=ansible_facts["default_ipv4"]["address"]
  - debug: var=ansible_facts["distribution_file_variety"]
  - debug: var=ansible_facts["distribution"]
  - debug: var=ansible_facts["distribution_version"]
  - debug: var=ansible_facts["env"]["user"]
  #- debug: var=ansible_facts["eth0"]["device"]
  - debug: var=ansible_facts["hostname"]
  - debug: var=ansible_facts["interfaces"]
  - debug: var=ansible_facts["machine"]
  - debug: var=ansible_facts["memory_total_mb"]
  - debug: var=ansible_facts["nodename"]
  - debug: var=ansible_facts["os_family"]
  - debug: var=ansible_facts["nodename"]
  - debug: var=ansible_facts["nodename"]
  - debug: var=ansible_facts["nodename"]
  - debug: var=ansible_facts["nodename"]


  #- debug: var=ansible_facts 

- hosts: bootstrap
  gather_facts: true
  vars_files:
  - ~/ansible/vault.yml
  tags: bootstrap
  become: true
  tasks:
  - name: "debug facts"
    tags: openresolv
    debug: var=ansible_facts["machine"]
  # - name: "debug facts"
  #   tags: openresolv
  #   debug: var=ansible_facts
  roles:
  - role: gantsign.keyboard
    vars: 
      # European keyboard model (pc105 is widely used outside Europe as well)
      keyboard_model: pc105
      # Layout for belgium (er, which Belgium ?)
      keyboard_layout: be
  - bootstrap

- hosts: all
  #tags: always
  gather_facts: true
  become: true

  pre_tasks:
  # - name: "debug inventory"
  #   debug: var=inventory_hostname

  # - debug: var=ansible_facts["machine"]
  #   tags: debugecho

#  - debug: var=ansible_facts
  # - debug: var=ansible_facts["os_family"]
  #   tags: debugecho

  # - name: "test echo commmand"
  #   tags: debugecho
  #   command: echo "this is a test of the echo command"
  #   register: cmdoutput
  #   when: ansible_facts["os_family"] != "Windows"

  # - debug: var=cmdoutput
  #   tags: debugecho
      
#  - name: update repository index (CentOS)
#    tags: always
#    dnf:
#      update_cache: yes
#    changed_when: false
#    when: ansible_distribution == "CentOS"
#
   # - tags: debug40
  #   debug:
  #     var: ansible_facts
  #     #var: ansible_facts["cmdline"]

  - name: update repository index (Ubuntu)
    tags: debug42
    apt:
      update_cache: yes
      upgrade: "yes"
    changed_when: false
    #when: ansible_distribution == "Ubuntu"
    #when: ansible_os_family != "Windows"
  
# - hosts: all
#   tags: facts
#   gather_facts: true
#   vars_files:
#   - ~/ansible/vault.yml
#   become: true
#   tasks:
#   - debug: var=ansible_facts
    
- hosts: all
  tags: base
  gather_facts: true
  vars_files:
  - ~/ansible/vault.yml
  become: true
  roles:
    - base

- hosts: pi
  gather_facts: true
  vars_files:
  - ~/ansible/vault.yml
  tags: pi
  become: true
  roles:
  - pi

- hosts: laptops
  gather_facts: false
  tags: laptops
  become: true
  roles: 
    - laptops

- hosts: postfix
  vars_files:
  - ~/ansible/vault.yml
  gather_facts: true
  tags: postfix
  become: true
  roles:
    - geerlingguy.postfix
    - postfix

- hosts: web_servers
  gather_facts: false
  tags: web_servers
  become: true
  roles: 
    - web_servers

- hosts: db_servers
  vars_files:
  - ~/ansible/vault.yml
  #gather_facts: false
  tags: db_servers
  become: true
  roles:
  - db_servers

- hosts: monitor
  vars_files:
  - ~/ansible/vault.yml
  gather_facts: false
  tags: monitor
  become: true
  roles: 
    - monitor
    
- hosts: watchdog
  name: install watchdog
  tags: watchdog, conda_watchdog
  vars_files:
  - ~/ansible/vault.yml
  gather_facts: true
  become: true
  roles: 
    - evandam.conda
    - watchdog
  # tasks:
  # - name: Create a conda environment - watchdog
  #   tags: conda_watchdog
  #   conda:
  #     name: python
  #     version: "3.7"
  #     environment: /home/toto/.conda/envs/watchdog
  #     state: present
  #     executable: /opt/conda/bin/conda
  #   when: ansible_facts["lsb"]["id"] != "Raspbian"

  # - name: Install some packages in conda environment - watchdog
  #   tags: conda_watchdog
  #   conda:
  #     name:
  #       - numpy
  #       - requests
  #     environment: /home/toto/.conda/envs/watchdog
  #     executable: /opt/conda/bin/conda
  #   when: ansible_facts["lsb"]["id"] != "Raspbian"

- hosts: vnc_servers
  tags: vnc_servers
  become: true
  roles: 
    - vnc_servers


# - hosts: x_servers
#   gather_facts: false
#   tags: x_servers
#   become: true
#   roles:
#     - x_servers

- hosts: windows
  tags: windows
  gather_facts: false
  vars_files:
  - ~/ansible/vault.yml
  roles:
    - windows

- hosts: whos_on_my_network
  gather_facts: false
  tags: whos_on_my_network
  become: true
  roles: 
    - whos_on_my_network

- hosts: frigo
  name: install frigo
  tags: frigo
  vars_files:
  - ~/ansible/vault.yml
  gather_facts: true
  become: true
  roles: 
    - evandam.conda
    - frigo
  # tasks:
  # - name: Update conda
  #   conda:
  #     name: conda
  #     state : latest
  #     executable: /opt/conda/bin/conda
  #   when: ansible_facts["lsb"]["id"] != "Raspbian"

  # - name: Install R, using a versioned name
  #   conda:
  #     name: r-base=3.5.0

#
#- hosts: file_servers
#  tags: file_servers
#  become: true
#  roles:
#    - file_servers

##-------------------------------------------------
#- hosts: all
#  become: true
#  vars_files:
#  - ~/ansible/info.yml
#
#  pre_tasks:
#
##  - debug:
##      var: ansible_facts["cmdline"]
##  - debug:
##      var: ansible_facts["machine"]
##  - debug:
##      var: ansible_facts["machine"]|type_debug
##  - debug:
##      var: ansible_distribution

# - hosts: ansible_servers
#   gather_facts: false
#   tags: ansible_servers
#   become: true
#   roles:
#     - ansible_servers

#- hosts: workstations
#  tags: workstations
#  become: true
#  roles:
#    - workstations
#

# - hosts: conda
#   gather_facts: true
#   vars_files:
#   - ~/ansible/vault.yml
#   tags: conda
#   become: true
#   roles: 
#     - evandam.conda
#     - conda

# - hosts: vagrant
#   #gather_facts: false
#   tags: vagrant
#   become: true
#   roles:
#     - vagrant



- hosts: all
  name: install watchdog
  tags: success_msg
  vars_files:
  - ~/ansible/vault.yml
  gather_facts: true
  become: true
  tasks:
    - name: "get hostname"
      shell: "hostname"
      register: shelloutput

    - name: sending mail to confirm completion of ansible script
      tags: confirm_success
      mail:
        host: smtp.gmail.com
        port: 587
        username: "{{ vault_toto_mailer }}@gmail.com"
        password: "{{ vault_toto_mailer_pw }}"
        to: 
        - "{{ vault_toto_email }}@gmail.com"
        #- "eric.derruine@ec.europa.eu"
        subject: System {{ ansible_hostname }} has been successfully provisioned.
        body: "System {{ ansible_hostname }} has been successfully provisioned.  Sent from {{ shelloutput.stdout }}"
      #delegate_to: localhost

