---
#- name: install httpd package (CentOS)
#  tags: apache,centos,httpd
#  dnf:
#    name:
#      - httpd
#      - php
#    state: latest
#  when: ansible_distribution == "CentOS"
#
#- name: start and enable httpd (CentOS)
#  tags: apache,centos,httpd
#  service:
#    name: httpd
#    state: started
#    enabled: yes
#  when: ansible_distribution == "CentOS"

#- name: restart httpd (CentOS)
#  tags: apache,centos,httpd
#  service:
#    name: httpd
#    state: restarted
#  when: httpd.changed    

- name: install apache2 package (Ubuntu)
  tags: apache,apache2,ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
      - php 
      - phpmyadmin 
      # - php-mbstring php-zip php-gd php-json php-curl
    state: latest
  #when: ansible_distribution == "Ubuntu"

#- name: "open firewall if needed"
#  firewalld: 
#    service: "{{ item }}"
#    permanent: yes
#    state: enabled
#    immedidae: yes
#  loop:
#    - http
#    - https


#- name: change e-mail address for admin
#  tags: apache,centos,httpd
#  lineinfile:
#    path: /etc/httpd/conf/httpd.conf
#    regexp: '^ServerAdmin'
#    line: ServerAdmin somebody@somewhere.net
#  when: ansible_distribution == "CentOS"
#  register: httpd

#- name: copy html file for site
#  tags: apache,apache,apache2,httpd
#  copy:
#    src: default_site.html
#    dest: /var/www/html/index.html
#    owner: root
#    group: root
#    mode: '0644'

- name: "make sure apache is restarted"
  tags: start_and_enable_apache2
  service:
    name: apache2
    state: restarted
    enabled: yes

- name: Download php Composer
  # https://symfonycasts.com/screencast/ansible/ansible-composer#installing-composer-with-script
  script: scripts/install_composer.sh

- name: Move php Composer
  become: true
  command: mv composer.phar /usr/local/bin/composer

- name: Set permissions on Composer
  become: true
  file:
    path: /usr/local/bin/composer
    mode: "a+x"