---
#- name: "install some packages"
#  package:
#    name: npm
#    state: latest

- name: install repo monitor for toto
  tags: repomon
  ansible.builtin.git: repo={{ item.repo }} dest={{ item.dest }} clone=yes update=no force=no
  with_items:
  - { repo: 'https://github.com/toto240325/monitor.git', dest: '/home/toto/monitor' }
  register: repo_monitor

- name: change ownership
  tags: repomon
  file: path={{ item.path }} owner="toto" group="toto" state=directory recurse=yes mode="u=rwX,g=rX,o=rX"
  with_items:
  - { path: "/home/toto/monitor" }
  #register: output_chown
  when: repo_monitor.changed

- name: "initialise DB in separate location"
  file: 
    path: /home/toto/db
    state: directory
    owner: toto
    group: toto
  when: repo_monitor.changed

#- name: cron job to launch whos_on_my_network watcher under root
#  cron:
#    user: root
#    name: "cron whos_on_my_network watcher"
#    special_time: reboot
#    #minute: "*/10"
#    job: ". /home/toto/whos_on_my_network/run_whos_watcher >> ~/whos_on_my_network_watcher.log"
#
#- name: cron job to launch whos_on_my_network webserver under root
#  cron:
#    user: root
#    name: "cron whos_on_my_network_webserver"
#    special_time: reboot
#    #minute: "*/10"
#    job: ". /home/toto/whos_on_my_network/run_whos_webserver >> ~/whos_on_my_network_webserver.log"


