---

- name: copy basic files to user vagrant - id_ed25519_toto.pub, id_ed25519_toto, .vimrc, .tmux.conf, .bash_aliases
  copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }} owner=vagrant group=vagrant
  with_items:
  - { src: 'id_ed25519_toto.pub',    dest: '/home/vagrant/.ssh/', mode: '0644' }
  - { src: '~/.ssh/id_ed25519_toto', dest: '/home/vagrant/.ssh/', mode: '0600' }
  - { src: '.vimrc',                 dest: '/home/vagrant/.ssh/', mode: '0644' }
  - { src: '.tmux.conf',             dest: '/home/vagrant/.ssh/', mode: '0644' }
  - { src: '.bash_aliases',          dest: '/home/vagrant/.ssh/', mode: '0644' }

- name: add ssh key for vagrant (ed_25519_toto_local)
  authorized_key:
    user: vagrant
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPplB13Opukct+t9O1nbRskrsFSnHPIktMYLuDjilXSV toto@local"

