---
 
- name: copy basic files to user vagrant - id_ed25519_toto.pub, id_ed25519_toto, .vimrc, .tmux.conf, .bash_aliases
  copy: src=~/ansible/roles/base/files/.vimrc dest=/home/vagrant/ owner=vagrant group=vagrant mode=0644
- copy: src=~/ansible/roles/base/files/.tmux.conf dest=/home/vagrant/ owner=vagrant group=vagrant mode=0644
- copy: src=~/ansible/roles/base/files/.bash_aliases dest=/home/vagrant/.bash_aliases owner=vagrant group=vagrant mode=0644

- name: add ssh key for vagrant (ed_25519_toto_local)
  authorized_key:
    user: vagrant
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPplB13Opukct+t9O1nbRskrsFSnHPIktMYLuDjilXSV toto@local"

