---
#https://www.linkedin.com/pulse/configure-postfix-realyhost-send-e-mail-help-ansible-rahangdale/

- name: adding required lines in /etc/postfix/main.cf file
  tags: debugpostfix
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    

- name: configuring postfix sasl creds
  tags: debug999
  copy:
    content: '[smtp.gmail.com]:587 {{ vault_toto_mailer }}:{{ vault_toto_mailer_pw}}'
#    content: 'smtp.gmail.com:587 {{ vault_toto_mailer }}:{{ vault_toto_mailer_pw}}'
    dest: /etc/postfix/sasl_passwd
    owner: root
    group: postfix
    mode: '0640'

- name: generate postfix lookup table
  command: postmap /etc/postfix/sasl_passwd

# # not clear whether and why this step is absolutely necessary, but it seems to unblock some use cases
# - name: add smtpd_relay_restrictions parameter
#   lineinfile:
#     path: "/etc/postfix/main.cf"
#     state: present
#     #regexp: "^HandleLidSwitch="
#     line: "smtpd_relay_restrictions=check_relay_domains"

- name: enabling and starting postfix service
  service:
    name: postfix
    state: restarted

- name: "get hostname"
  shell: "hostname"
  register: shelloutput

# - name: "debug shell output"
#   debug: var=shelloutput.stdout

- name: sending mail to test@gmail.com
  tags: debugmail
  mail:
    host: smtp.gmail.com
    port: 587
    username: "{{ vault_toto_mailer }}@gmail.com"
    password: "{{ vault_toto_mailer_pw }}"
    to: 
    - "{{ vault_toto_email }}@gmail.com"
    - "eric.derruine@ec.europa.eu"
    subject: Postfix installed correctly on {{ ansible_hostname }}.
    body: "Postfix installed correctly on {{ ansible_hostname }}.  Sent from {{ shelloutput.stdout }}"
  #delegate_to: localhost

