---
## Ubuntu16.04: rmmod: ERROR: Module ipv6 is builtin.

- name: rmmodipv6
  command: rmmod ipv6
  failed_when: false
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "lxc" or ansible_virtualization_type == "docker")
        )

- name: modipv6
  command: modprobe ipv6
  failed_when: false
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "lxc" or ansible_virtualization_type == "docker")
        )
- name: restart network
  service: name=network state=restarted
  when: >
    not (ansible_virtualization_type is defined and ansible_virtualization_type == "docker") and
    not (ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 8)
- name: restart NetworkManager
  service: name=NetworkManager state=restarted
  when: >
    not (ansible_virtualization_type is defined and ansible_virtualization_type == "docker") and
    ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 8
- name: grub2-mkconfig
  command: grub2-mkconfig -o /boot/grub2/grub.cfg
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "lxc" or ansible_virtualization_type == "docker")
        )