---
- name: install repo watchdog for toto (dev)
  tags: repowatchdog_dev
  ansible.builtin.git: repo={{ item.repo }} dest={{ item.dest }} clone=yes update=no force=no
  with_items:
  - { repo: 'https://github.com/toto240325/watchdog.git', dest: '/home/toto/watchdog' }
  register: repo_watchdog_dev

- name: make sure .git/config is set to git@github:toto240325/<prj>.git... instead of https://github.com/toto240325/<prj>.git to allow edit and push back to git
  tags: repowatchdog_dev
  replace: path="{{ item }}/.git/config" regexp="https://github.com/toto240325" replace="git@github.com:toto240325"
  with_items:
  - "/home/toto/watchdog"

- name: Install requirements for watchdog
  tags: watchdog_req_dev
  pip: 
    requirements: /home/toto/watchdog/requirements.txt
    virtualenv: /home/toto/watchdog/venv
    #virtualenv_python: python3.7
    virtualenv_python: python3

- name: remove old venv
  file:
    path: /home/toto/venv/watchdog
    state: absent

- name: check if watchdog params.py already exists
  tags: watchdog_params_dev
  stat:
    path: /home/toto/watchdog/params.py
  register: stat_result

- name: "Copy params.py"
  tags: watchdog_params_dev
  template:
    src: "files/params.py.j2"
    dest: "/home/toto/watchdog/params.py"
  when: not stat_result.stat.exists

- name: update the list of server that mustBeUp
  tags: update_mustBeUp
  blockinfile:
    path: /home/toto/watchdog/params.py
    block: |
      mustBeup block
      should be put here
    marker: "# {mark} ANSIBLE MANAGED BLOCK watchdog_mustBeUp"
    #insertbefore: 
  #notify: do_this_after_mustBeUp_updated


- name: set ownership of log files (some log files are create by root in /home/toto)
  tags: fix_ownership_logs
  become: True
  file: path="/home/toto/watchdog" owner=toto group=toto state=touch
  with_items:
  - watchdog.log
  - watchdog.txt

- name: change ownership
  tags: repowatchdog
  file: path={{ item.path }} owner="toto" group="toto" state=directory recurse=yes mode="u=rwX,g=rX,o=rX"
  with_items:
  - { path: "/home/toto/watchdog" }
  #register: output_chown
  #when: repo_watchdog_dev.changed

# - name: cron job to update the git repository
#   tags: pull_watchdog
#   cron:
#     user: toto
#     name: "pull_watchdog"
#     special_time: reboot
#     # minute: "24"
#     # hour: "21"
#     job: "sleep 90 && cd ~/watchdog && date >> ~/misc.log && git pull https://github.com/toto240325/watchdog.git >> ~/misc.log 2>&1"
#     state: absent

# - name: force git pull watchdog
#   tags: force_pull_watchdog
#   shell:
#     cmd: 'su -c "cd ~/watchdog && date >> ~/misc.log && git pull https://github.com/toto240325/watchdog.git >> ~/misc.log" toto'
  

# - name: set the SHELL cron variable
#   tags: debug49
#   community.general.cronvar:
#     user: toto
#     name: SHELL
#     value: /bin/bash
    
# - name: set the BASH_ENV cron variable
#   tags: debug49
#   community.general.cronvar:
#     user: toto
#     name: BASH_ENV
#     value: /home/toto/.bashrc_conda
#     insertafter: SHELL
    
# - name: cron job to launch watchdog under toto
#   tags: debug49
#   cron:
#     user: toto
#     name: "watchdog"
#     #special_time: reboot
#     #minute: "*/5"
#     minute: "30"
#     job: "conda activate /home/toto/.conda/envs/watchdog; python /home/toto/watchdog/watchdog.py 2>&1 >> /home/toto/watchdog.log; conda deactivate"
#     state: absent

# - name: change ownership to toto:toto
#   tags: debug111
#   file: path={{ item.path }} owner="toto" group="toto" state=directory recurse=yes
#   with_items:
#   - { path: "/home/toto/conda/" }
#   when: ansible_facts["lsb"]["id"] != "Raspbian"

# - name: cron job to launch watchdog under root
#   tags: watchdog_cron
#   cron:
#     user: root
#     name: "watchdog"
#     #special_time: reboot
#     minute: "*/5"
#     #minute: "30"
#     job: ". /home/toto/venv/watchdog/bin/activate && python /home/toto/watchdog/watchdog.py  >> /home/toto/watchdog.log"
#   #when: ansible_facts["lsb"]["id"] == "Raspbian"

