---
- name: "install some packages"
  package:
    name: npm
    state: latest

- name: install repo whos_on_my_network for toto
  #become: true
  ansible.builtin.git: repo={{ item.repo }} dest={{ item.dest }} clone=yes update=yes force=no
  with_items:
  - { repo: 'https://github.com/toto240325/whos_on_my_network.git', dest: '/home/toto/whos_on_my_network' }
  register: repo_whos

- name: "install pip flask (for whos_on_my_network)"
  pip:
    name: Flask
    state: latest
    virtualenv: /home/toto/Envs/whos_on_my_network

- name: "after-install of repo of whos_on_my_network (pip requirements)"
  pip:
    requirements: /home/toto/whos_on_my_network/requirements.txt
    virtualenv: /home/toto/Envs/whos_on_my_network
  
- name: "ad hoc shell : cd webapp && npm i && npm run build"
  remote_user: toto
  shell: "cd /home/toto/whos_on_my_network/webapp && npm i && npm run build"
  register: shell_output

#- debug: var=shell_output

