---

- name: install new packages
  tags: power_packages_dev
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - livemedia-utils  # openRTSP
    - ffmpeg
    - tesseract-ocr

- name: install repo power for toto (dev)
  tags: repopower_dev
  ansible.builtin.git: repo={{ item.repo }} dest={{ item.dest }} clone=yes update=no force=no
  with_items:
  - { repo: 'https://github.com/toto240325/power.git', dest: '/home/toto/power' }
  register: repo_power_dev

- name: make sure .git/config is set to git@github:toto240325/<prj>.git... instead of https://github.com/toto240325/<prj>.git to allow edit and push back to git
  tags: repopower_dev
  replace: path="{{ item }}/.git/config" regexp="https://github.com/toto240325" replace="git@github.com:toto240325"
  with_items:
  - "/home/toto/power"

- name: install latest version of pip
  tags: pip_latest_for_power
  pip:
    virtualenv: /home/toto/power/venv
    virtualenv_python: python3
    name: pip
    state: latest

- name: Install requirements for power
  tags: power_req_dev
  pip: 
    requirements: /home/toto/power/requirements.txt
    virtualenv: /home/toto/power/venv
    #virtualenv_python: python3.7
    virtualenv_python: python3

- name: check if power params.py already exists
  tags: power_params_dev
  stat:
    path: /home/toto/power/params.py
  register: stat_result

- name: "Copy params.py"
  tags: power_params_dev
  template:
    src: "files/params.py.j2"
    dest: "/home/toto/power/params.py"
  when: not stat_result.stat.exists

- name: set ownership of log files (some log files are create by root in /home/toto)
  tags: fix_ownership_logs
  become: True
  file: path="/home/toto/power" owner=toto group=toto state=touch
  with_items:
  - power.log
  - power.txt

- name: change ownership
  tags: repopower
  file: path={{ item.path }} owner="toto" group="toto" state=directory recurse=yes mode="u=rwX,g=rX,o=rX"
  with_items:
  - { path: "/home/toto/power" }
  #register: output_chown
  #when: repo_power_dev.changed

