---
#- name: "install some packages"
#  package:
#    name: npm
#    state: latest

- name: install repo frigo for toto
  tags: repofrigo
  ansible.builtin.git: repo={{ item.repo }} dest={{ item.dest }} clone=yes # update=yes force=yes
  with_items:
  - { repo: 'https://github.com/toto240325/frigo.git', dest: '/home/toto/frigo' }
  register: repo_frigo

- name: make sure .git/config is set to git@github:toto240325/<prj>.git... instead of https://github.com/toto240325/<prj>.git to allow edit and push back to git
  tags: repofrigo
  replace: path="{{ item }}/.git/config" regexp="https://github.com/toto240325" replace="git@github.com:toto240325"
  with_items:
  - "/home/toto/frigo"

# - name: cron job to update the git frigo repository
#   tags: pull_frigo
#   cron:
#     user: toto
#     name: "pull_frigo"
#     special_time: reboot
#     # minute: "24"
#     # hour: "21"
#     job: "cd ~/frigo && git pull https://github.com/toto240325/frigo.git >> /home/toto/misc.log"
#   # when: ansible_facts["lsb"]["id"] != "Raspbian"

# - name: force git pull frigo
#   tags: force_pull_frigo
#   shell:
#     cmd: 'su -c "cd ~/frigo && date >> ~/misc.log && git pull https://github.com/toto240325/frigo.git >> ~/misc.log" toto'
  

- name: check if frigo params.py already exists
  tags: frigo_params
  stat:
    path: /home/toto/frigo/params.py
  register: stat_result

- name: "Copy frigo params.py"
  tags: frigo_params
  template:
    src: "files/params.py.j2"
    dest: "/home/toto/frigo/params.py"
  when: not stat_result.stat.exists

- name: Install requirements for frigo
  tags: frigo_req
  pip: 
    requirements: /home/toto/frigo/requirements.txt
    virtualenv: /home/toto/venv/frigo
    #virtualenv_python: python3.7
    virtualenv_python: python3
  #when: ansible_facts["lsb"]["id"] == "Raspbian"

- name: change ownership frigo directory to toto:toto
  tags: frigo_ownership
  file: path={{ item.path }} owner="toto" group="toto" state=directory recurse=yes mode="u=rwX,g=rX,o=rX"
  with_items:
  - { path: "/home/toto/venv/" }
  #register: output_chown
  #when: repo_frigo.change

- name: cron job to launch frigo under root
  tags: frigo_cron
  cron:
    user: root
    name: "frigo"
    special_time: reboot
    #minute: "*/5"
    #minute: "30"
    job: "sleep 60 && . /home/toto/venv/frigo/bin/activate && python /home/toto/frigo/frigo.py  >> /home/toto/frigo.log"
  #when: ansible_facts["lsb"]["id"] == "Raspbian"

