# ---
# - name: install packages specific to ansible
#   package:
#     name: "{{ item }}"
#     state: latest
#   with_items:
#     - ansible
#     - ansible-lint
#     - sshpass            # this is need to manage windows machines
#   #when: ansible_distribution in ["Ubuntu","Debian"] and ansible_distribution_version == "20.04"
#   #when: no

