---
- name: install basic packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - ansible
    - ansible-lint
    - vim
    - unzip
    - tmux
    - p7zip-full
    - git
    - htop
    - python3-pip
  #when: ansible_distribution in ["Ubuntu","Debian"] # and ansible_distribution_version == "20.04"
  when: no

- name: install new packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - sqlite3
  when: yes
  #when: ansible_distribution in ["Ubuntu","Debian"] # and ansible_distribution_version == "20.04"

- name: sqlite3 by defaut
  #prerequisite:
  #ansible-galaxy collection install community.general
  community.general.alternatives:
    name: sqlite
    path: /usr/bin/pip3
    link: /usr/local/bin/sqlite

- name: python3 by defaut
  #prerequisite:
  #ansible-galaxy collection install community.general
  community.general.alternatives:
    name: python
    path: /usr/bin/python3
    link: /usr/local/bin/python

- name: pip3 by defaut
  #prerequisite:
  #ansible-galaxy collection install community.general
  community.general.alternatives:
    name: pip
    path: /usr/bin/pip3
    link: /usr/local/bin/pip

- name: upgrade pip to latest version
  pip:
    name: pip
    executable: pip3
    state: latest

- name: "install pip virtualenv"
  pip:
    name: virtualenv
    state: latest
    #virtualenv: /my_app/venv

- include: toto_user.yml
  tags: toto

- include: ansible_user.yml
