---
- name: install basic packages
  package:
    name:
      - ansible
      - vim
      - unzip
      - tmux
      - p7zip-full
      - git
      - htop
    state: latest
  when: ansible_distribution in ["Ubuntu","Debian"] # and ansible_distribution_version == "20.04"

- name: python3 by defaut
  community.general.alternatives:
    name: python
    path: /usr/bin/python3
    link: /usr/local/bin/python

- include: user_toto.yml

- include: user_ansible.yml
