---

#- debug: msg="debug test"
#
#- name: shell test
#  shell: pwd
#  register: myoutput
#
#- debug: var=myoutput

- name: create toto user
  user:
    name: toto
    password: "{{ toto_password | password_hash('sha512','myOwnSalt') }}"
    #password: "{{ 'password' | password_hash('sha512') }}"
    update_password: on_create
    shell: /bin/bash
    state: present

- name: add ssh key for toto
  authorized_key:
    user: toto
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJEa4zZ/C4s4rNNWk6raYFpLH3XVKh393wNX1iWTCcNG toto240325@gmail.com"

- name: add sudoers file for toto
  copy:
    src: sudoer_toto
    dest: /etc/sudoers.d/toto
    owner: root
    group: root
    mode: 0440

- name: copy basic files to user toto - id_ed25519_toto.pub, id_ed25519_toto, .vimrc, .tmux.conf, .bash_aliases
  copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }} owner=toto group=toto
  with_items:
  - { src: 'id_ed25519_toto.pub',    dest: '/home/toto/.ssh/',  mode: '0644' }
  - { src: '~/.ssh/id_ed25519_toto', dest: '/home/toto/.ssh/',  mode: '0600' }
  - { src: '.vimrc',                 dest: '/home/toto/',       mode: '0644' }
  - { src: '.tmux.conf',             dest: '/home/toto/',       mode: '0644' }
  - { src: '.bash_aliases',          dest: '/home/toto/',       mode: '0644' }

- name: setup some git global variables
  tags: debug2
  #remote_user: toto
  community.general.git_config: repo="/home/toto/test12" scope=global list_all=yes
  #community.general.git_config: name={{ item.name }} value={{ item.value }} repo="/home/toto/test12" scope=global list_all=yes
  with_items:
    - { name: 'user.name',  value: 'toto240325' }
    - { name: 'user.email', value: 'toto240325@gmail.com' }
  register: myoutput

- debug: var=myoutput
  tags: debug2

- name: install repo utils for toto 
  become: true
  tags: debug1
  ansible.builtin.git: repo={{ item.repo }} dest={{ item.dest }} clone=yes update=yes
  with_items:
  - { repo: 'https://github.com/toto240325/utils.git',              dest: '/home/toto/utils' }
  #- { repo: 'https://github.com/toto240325/ansible.git',           dest: '/home/toto/ansible' }
  - { repo: 'https://github.com/toto240325/whos-on-my-network.git', dest: '/home/toto/whos-on-my-network' }
  - { repo: 'https://github.com/toto240325/monitor.git',            dest: '/home/toto/monitor' }
  register: output_git

- debug: msg="after debug"
  tags: debug1

#- debug: var=output_git
#  tags: debug1

- name: change ownership
  tags: debug1
  file: path={{ item.path }} owner="toto" group="toto" state=directory recurse=yes
  with_items:
  - { path: "/home/toto/utils" }
  - { path: "/home/toto/ansible" }
  - { path: "/home/toto/whos-on-my-network" }
  - { path: "/home/toto/monitor" }
#  register: output_chown

#- debug: var=output_chown
#  tags: debug1

#- name: install cron job for toto
#  cron:
#    user: toto
#    name: "test toto cron"
#    minute: "*/10"
#    job: "/usr/bin/ansible-pull -o -U https://github.com/toto240325/ansible_pull_tutorial.git > /dev/null"

