---

- name: copy basic files to user ansible - id_ed25519_toto.pub, id_ed25519_toto, .vimrc, .tmux.conf, .bash_aliases
  copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }} owner=ansible group=ansible
  with_items:
  - { src: 'id_ed25519_toto.pub',    dest: '/home/ansible/.ssh/', mode: '0644' }
  - { src: '~/.ssh/id_ed25519_toto', dest: '/home/ansible/.ssh/', mode: '0600' }
  - { src: '.vimrc',                 dest: '/home/ansible/.ssh/', mode: '0644' }
  - { src: '.tmux.conf',             dest: '/home/ansible/.ssh/', mode: '0644' }
  - { src: '.bash_aliases',          dest: '/home/ansible/.ssh/', mode: '0644' }

- name: install ansible repo for ansible
  remote_user: ansible
  ansible.builtin.git:
    repo: https://github.com/toto240325/ansible.git
    dest: /home/ansible/ansible
    clone: yes
    update: yes


 
