---

#- debug: msg="debug test"
#
#- name: shell test
#  shell: pwd
#  register: myoutput
#
#- debug: var=myoutput

- name: create toto user
  user:
    name: toto
    password: "{{ toto_password | password_hash('sha512','myOwnSalt') }}"
    #password: "{{ 'password' | password_hash('sha512') }}"
    update_password: on_create
    shell: /bin/bash
    state: present

- name: add ssh key for toto
  authorized_key:
    user: toto
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJEa4zZ/C4s4rNNWk6raYFpLH3XVKh393wNX1iWTCcNG toto240325@gmail.com"

- name: add sudoers file for toto
  tags: always
  copy:
    src: sudoer_toto
    dest: /etc/sudoers.d/toto
    owner: root
    group: root
    mode: 0440

- name: copy basic files to user toto - id_ed25519_toto.pub, id_ed25519_toto, .vimrc, .tmux.conf, .bash_aliases
  copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }} owner=toto group=toto
  with_items:
  - { src: 'id_ed25519_toto.pub',    dest: '/home/toto/.ssh/', mode: '0644' }
  - { src: '~/.ssh/id_ed25519_toto', dest: '/home/toto/.ssh/', mode: '0600' }
  - { src: '.vimrc',                 dest: '/home/toto/.ssh/', mode: '0644' }
  - { src: '.tmux.conf',             dest: '/home/toto/.ssh/', mode: '0644' }
  - { src: '.bash_aliases',          dest: '/home/toto/.ssh/', mode: '0644' }

- name: install repo utils for toto
  remote_user: toto
  become: true
  ansible.builtin.git: repo={{ item.repo }} dest={{ item.dest }} clone=yes update=yes
  with_items:
  - { repo: 'https://github.com/toto240325/utils.git', dest: '/home/toto/utils'}
  - { repo: 'https://github.com/toto240325/ansible.git', dest: '/home/toto/ansible'}
  - { repo: 'https://github.com/toto240325/whos-on-my-network.git', dest: '/home/toto/whos-on-my-network'}


#- name : git clone utils
#  ansible.builtin.git:
#    #repo: git@github.com:toto240325/utils.git
#    repo: https://github.com/toto240325/utils.git
#    dest: /home/toto/utils
#    #key_file: /home/toto/.ssh/id_ed25519_toto

