---
#- name: install mariadb server package (CentOS)
#  tags: centos,db,mariadb
#  dnf:
#    name: mariadb
#    state: latest
#  when: ansible_distribution == "CentOS"

#- name: install mariadb server
#  tags: db,mariadb,ubuntu
#  apt:
#    name: mariadb-server
#    state: absent
#  when: ansible_distribution == "Ubuntu"

- name: "install mysql-server"
  #gather_facts: false
  package: name={{ item }} state=latest
  with_items:
    - mysql-server
 #   - mysql

- name: "start and enable mysql server"
  service:
    name: mysql
    state: started
    enabled: yes

- name: "install pymysql"
  pip:
    name: pymysql
    state: latest

- name: Create mysql database
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: 'root'
    login_password: "{{ toto_password | password_hash('sha512','myOwnSalt') }}"
    name: projectname
    state: present 

- name: Set MySQL root Password {{ toto_password }}
  no_log: true
  mysql_user:
#    login_host: 'localhost'
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: 'root'
    login_password: "{{ toto_password | password_hash('sha512','myOwnSalt') }}"
    name: 'root'
    password: "{{ toto_password | password_hash('sha512','myOwnSalt') }}"
    state: present

- name: "create mysql db"
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: 'root'
    login_password: "{{ toto_password | password_hash('sha512','myOwnSalt') }}"
    name: "{{ mysql_db }}"

